CREATE DATABASE marketplace;
\c marketplace;
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
CREATE TABLE Estado_Venta_Producto	(id			SERIAL		PRIMARY KEY, 
									 nombre		VARCHAR(20) NOT NULL);--activa--vendida-cancelada
CREATE TABLE Categorias			(id			SERIAL		PRIMARY KEY, 
								 nombre		VARCHAR(50) NOT NULL);
CREATE TABLE Regiones			(id			SERIAL		PRIMARY KEY, 
								 numero		VARCHAR(5)	NOT NULL,
								 nombre		VARCHAR(50) NOT NULL);
CREATE TABLE Comunas			(id			SERIAL		PRIMARY KEY, 
								 id_region	Integer		NOT NULL REFERENCES Regiones(id),
								 nombre		VARCHAR(50)	NOT NULL);								 
CREATE TABLE Usuarios			(id			SERIAL			PRIMARY KEY, 
								 nombre		VARCHAR(50)		NOT NULL,
								 apellido	VARCHAR(50)		NOT NULL,
								 email		VARCHAR(50)		NOT NULL UNIQUE,
								 clave		VARCHAR(250)	NOT NULL,
 								 telefono	VARCHAR(50));
CREATE TABLE Productos			(id					SERIAL			PRIMARY KEY,
								 fecha_publicacion	TIMESTAMP		NOT NULL,
								 nombre				VARCHAR(150)	NOT NULL,
								 descripcion		VARCHAR(350)	NOT NULL,
								 precio				Integer			NOT NULL,
								 stock				Integer			NOT NULL,
								 estado_venta		Integer			NOT NULL REFERENCES Estado_Venta_Producto(id),
								 --id_region			Integer			NOT NULL REFERENCES Regiones(id),
								 id_comuna			Integer			NOT NULL REFERENCES Comunas(id),
								 id_categoria		Integer			NOT NULL REFERENCES Categorias(id),
								 id_usuario			Integer			NOT NULL REFERENCES Usuarios(id));
CREATE TABLE Favoritos			(id				SERIAL	PRIMARY KEY,
								 id_usuario		Integer NOT NULL REFERENCES Usuarios(id),
								 id_producto	Integer NOT NULL REFERENCES Productos(id));
CREATE TABLE Imagenes_Producto	(id 			SERIAL		PRIMARY KEY, 
								 id_producto	Integer		NOT NULL REFERENCES Productos(id),
								 imagen			TEXT		NOT NULL);
CREATE TABLE Compra_Venta		(id					SERIAL		PRIMARY KEY,
								 id_usuario_compra	Integer		NOT NULL REFERENCES Usuarios(id),
								 id_usuario_venta	Integer		NOT NULL REFERENCES Usuarios(id),
								 id_producto		Integer		NOT NULL REFERENCES Productos(id),
								 precio_unidad		Integer		NOT NULL,
 								 cantidad			Integer		NOT NULL,
								 fecha_compra_venta	TIMESTAMP	NOT NULL);
CREATE TABLE Carrusel			(id				SERIAL			PRIMARY KEY, 
								 descripcion	VARCHAR(350)	NOT NULL,
								 imagen			TEXT			NOT NULL);

------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
INSERT INTO Estado_Venta_Producto values	(DEFAULT, 'activa'),
											(DEFAULT, 'cancelada');

INSERT INTO Categorias values	(DEFAULT, 'Electrónica'),
								(DEFAULT, 'Instrumentos musicales y accesorios'),
								(DEFAULT, 'Ropa y accesorios'),
								(DEFAULT, 'Hogar y jardín'),
								(DEFAULT, 'Belleza y cuidado personal'),
								(DEFAULT, 'Juguetes y juegos'),
								(DEFAULT, 'Deportes y actividades al aire libre'),
								(DEFAULT, 'Alimentos y bebidas'),
								(DEFAULT, 'Automóviles y motocicletas'),
								(DEFAULT, 'Salud y bienestar');

INSERT INTO Regiones values	(DEFAULT, 'XV', 'Arica y Parinacota'),
							(DEFAULT, 'I', 'Tarapacá'),
							(DEFAULT, 'II', 'Antofagasta'),
							(DEFAULT, 'III', 'Atacama'),
							(DEFAULT, 'IV', 'Coquimbo'),
							(DEFAULT, 'V', 'Valparaíso'),
							(DEFAULT, 'XIII', 'Metropolitana de Santiago'),
							(DEFAULT, 'VI', 'Libertador General Bernardo O''Higgins'),
							(DEFAULT, 'VII', 'Maule'),
							(DEFAULT, 'XVI', 'Ñuble'),
							(DEFAULT, 'VIII', 'Biobío'),
							(DEFAULT, 'IX', 'La Araucanía'),
							(DEFAULT, 'XIV', 'Los Ríos'),
							(DEFAULT, 'X', 'Los Lagos'),
							(DEFAULT, 'XI', 'Aysén del General Carlos Ibáñez del Campo'),
							(DEFAULT, 'XII', 'Magallanes y la Antártica Chilena');

INSERT INTO Comunas values 
(DEFAULT, 1, 'Arica'),
(DEFAULT, 1, 'Camarones'),
(DEFAULT, 1, 'General Lagos'),
(DEFAULT, 1, 'Putre'),

(DEFAULT, 2, 'Alto Hospicio'),
(DEFAULT, 2, 'Camiña'),
(DEFAULT, 2, 'Colchane'),
(DEFAULT, 2, 'Huara'),
(DEFAULT, 2, 'Iquique'),
(DEFAULT, 2, 'Pica'),
(DEFAULT, 2, 'Pozo Almonte'),
 
(DEFAULT, 3, 'Antofagasta'),
(DEFAULT, 3, 'Calama'),
(DEFAULT, 3, 'María Elena'),
(DEFAULT, 3, 'Mejillones'),
(DEFAULT, 3, 'Ollagüe'),
(DEFAULT, 3, 'San Pedro de Atacama'),
(DEFAULT, 3, 'Sierra Gorda'),
(DEFAULT, 3, 'Taltal'),
(DEFAULT, 3, 'Tocopilla'),

 
(DEFAULT, 4, 'Alto del Carmen'),
(DEFAULT, 4, 'Caldera'),
(DEFAULT, 4, 'Chañaral'),
(DEFAULT, 4, 'Copiapó'),
(DEFAULT, 4, 'Diego de Almagro'),
(DEFAULT, 4, 'Freirina'),
(DEFAULT, 4, 'Huasco'),
(DEFAULT, 4, 'Tierra Amarilla'),
(DEFAULT, 4, 'Vallenar'),

(DEFAULT, 5, 'Andacollo'),
(DEFAULT, 5, 'Canela'),
(DEFAULT, 5, 'Combarbalá'),
(DEFAULT, 5, 'Coquimbo'),
(DEFAULT, 5, 'Illapel'),
(DEFAULT, 5, 'La Higuera'),
(DEFAULT, 5, 'La Serena'),
(DEFAULT, 5, 'Los Vilos'),
(DEFAULT, 5, 'Monte Patria'),
(DEFAULT, 5, 'Ovalle'),
(DEFAULT, 5, 'Paihuano'),
(DEFAULT, 5, 'Punitaqui'),
(DEFAULT, 5, 'Río Hurtado'),
(DEFAULT, 5, 'Salamanca'),
(DEFAULT, 5, 'Vicuña'),
 
(DEFAULT, 6, 'Algarrobo'),
(DEFAULT, 6, 'Cabildo'),
(DEFAULT, 6, 'Calera'),
(DEFAULT, 6, 'Calle Larga'),
(DEFAULT, 6, 'Cartagena'),
(DEFAULT, 6, 'Casablanca'),
(DEFAULT, 6, 'Catemu'),
(DEFAULT, 6, 'Concón'),
(DEFAULT, 6, 'El Quisco'),
(DEFAULT, 6, 'El Tabo'),
(DEFAULT, 6, 'Hijuelas'),
(DEFAULT, 6, 'Isla de Pascua'),
(DEFAULT, 6, 'Juan Fernández'),
(DEFAULT, 6, 'La Cruz'),
(DEFAULT, 6, 'La Ligua'),
(DEFAULT, 6, 'Limache'),
(DEFAULT, 6, 'Llaillay'),
(DEFAULT, 6, 'Los Andes'),
(DEFAULT, 6, 'Nogales'),
(DEFAULT, 6, 'Olmué'),
(DEFAULT, 6, 'Panquehue'),
(DEFAULT, 6, 'Papudo'),
(DEFAULT, 6, 'Petorca'),
(DEFAULT, 6, 'Puchuncaví'),
(DEFAULT, 6, 'Putaendo'),
(DEFAULT, 6, 'Quillota'),
(DEFAULT, 6, 'Quilpué'),
(DEFAULT, 6, 'Quintero'),
(DEFAULT, 6, 'Rinconada'),
(DEFAULT, 6, 'San Antonio'),
(DEFAULT, 6, 'San Esteban'),
(DEFAULT, 6, 'San Felipe'),
(DEFAULT, 6, 'Santa María'),
(DEFAULT, 6, 'Santo Domingo'),
(DEFAULT, 6, 'Valparaíso'),
(DEFAULT, 6, 'Villa Alemana'),
(DEFAULT, 6, 'Viña del Mar'),
(DEFAULT, 6, 'Zapallar'),
 
(DEFAULT, 7, 'Alhué'),
(DEFAULT, 7, 'Buin'),	
(DEFAULT, 7, 'Calera de Tango'),
(DEFAULT, 7, 'Cerrillos'),
(DEFAULT, 7, 'Cerro Navia'),	
(DEFAULT, 7, 'Colina'),
(DEFAULT, 7, 'Conchalí'),
(DEFAULT, 7, 'Curacaví'),
(DEFAULT, 7, 'El Bosque'),
(DEFAULT, 7, 'El Monte'),
(DEFAULT, 7, 'Estación Central'),
(DEFAULT, 7, 'Huechuraba'),
(DEFAULT, 7, 'Independencia'),	
(DEFAULT, 7, 'Isla de Maipo'),	
(DEFAULT, 7, 'La Cisterna'),	
(DEFAULT, 7, 'La Florida'),	
(DEFAULT, 7, 'La Granja'),	
(DEFAULT, 7, 'Lampa'),	
(DEFAULT, 7, 'La Pintana'),	
(DEFAULT, 7, 'La Reina'),	
(DEFAULT, 7, 'Las Condes'),	
(DEFAULT, 7, 'Lo Barnechea'),	
(DEFAULT, 7, 'Lo Espejo'),	
(DEFAULT, 7, 'Lo Prado'),	
(DEFAULT, 7, 'Macul'),	
(DEFAULT, 7, 'Maipú'),	
(DEFAULT, 7, 'María Pinto'),	
(DEFAULT, 7, 'Melipilla'),	
(DEFAULT, 7, 'Ñuñoa'),	
(DEFAULT, 7, 'Padre Hurtado'),	
(DEFAULT, 7, 'Paine'),	
(DEFAULT, 7, 'Pedro Aguirre Cerda'),	
(DEFAULT, 7, 'Peñaflor'),	
(DEFAULT, 7, 'Peñalolén'),	
(DEFAULT, 7, 'Pirque'),	
(DEFAULT, 7, 'Providencia'),	
(DEFAULT, 7, 'Pudahuel'),	
(DEFAULT, 7, 'Puente Alto'),	
(DEFAULT, 7, 'Quilicura'),	
(DEFAULT, 7, 'Quinta Normal'),	
(DEFAULT, 7, 'Recoleta'),	
(DEFAULT, 7, 'Renca'),	
(DEFAULT, 7, 'San Bernardo'),	
(DEFAULT, 7, 'San Joaquín'),	
(DEFAULT, 7, 'San José de Maipo'),	
(DEFAULT, 7, 'San Miguel'),	
(DEFAULT, 7, 'San Pedro'),	
(DEFAULT, 7, 'San Ramón'),	
(DEFAULT, 7, 'Santiago'),	
(DEFAULT, 7, 'Talagante'),	
(DEFAULT, 7, 'Tiltil'),	
(DEFAULT, 7, 'Vitacura'),	

(DEFAULT, 8, 'Chépica'),
(DEFAULT, 8, 'Chimbarongo'),
(DEFAULT, 8, 'Codegua'),
(DEFAULT, 8, 'Coínco'),
(DEFAULT, 8, 'Coltauco'),
(DEFAULT, 8, 'Doñihue'),
(DEFAULT, 8, 'Graneros'),
(DEFAULT, 8, 'La Estrella'),
(DEFAULT, 8, 'Las Cabras'),
(DEFAULT, 8, 'Litueche'),
(DEFAULT, 8, 'Lolol'),
(DEFAULT, 8, 'Machalí'),
(DEFAULT, 8, 'Malloa'),
(DEFAULT, 8, 'Marchihue'),
(DEFAULT, 8, 'Mostazal'),
(DEFAULT, 8, 'Nancagua'),
(DEFAULT, 8, 'Navidad'),
(DEFAULT, 8, 'Olivar'),
(DEFAULT, 8, 'Palmilla'),
(DEFAULT, 8, 'Paredones'),
(DEFAULT, 8, 'Peralillo'),
(DEFAULT, 8, 'Peumo'),
(DEFAULT, 8, 'Pichidegua'),
(DEFAULT, 8, 'Pichilemu'),
(DEFAULT, 8, 'Placilla'),
(DEFAULT, 8, 'Pumanque'),
(DEFAULT, 8, 'Quinta de Tilcoco'),
(DEFAULT, 8, 'Rancagua'),
(DEFAULT, 8, 'Rengo'),
(DEFAULT, 8, 'Requínoa'),
(DEFAULT, 8, 'San Fernando'),
(DEFAULT, 8, 'Santa Cruz'),
(DEFAULT, 8, 'San Vicente'),

(DEFAULT, 9, 'Cauquenes'),
(DEFAULT, 9, 'Chanco'),
(DEFAULT, 9, 'Colbún'),
(DEFAULT, 9, 'Constitución'),
(DEFAULT, 9, 'Curepto'),
(DEFAULT, 9, 'Curicó'),
(DEFAULT, 9, 'Empedrado'),
(DEFAULT, 9, 'Hualañé'),
(DEFAULT, 9, 'Licantén'),
(DEFAULT, 9, 'Linares'),
(DEFAULT, 9, 'Longaví'),
(DEFAULT, 9, 'Maule'),
(DEFAULT, 9, 'Molina'),
(DEFAULT, 9, 'Parral'),
(DEFAULT, 9, 'Pelarco'),
(DEFAULT, 9, 'Pelluhue'),
(DEFAULT, 9, 'Pencahue'),
(DEFAULT, 9, 'Rauco'),
(DEFAULT, 9, 'Retiro'),
(DEFAULT, 9, 'Río Claro'),
(DEFAULT, 9, 'Romeral'),
(DEFAULT, 9, 'Sagrada Familia'),
(DEFAULT, 9, 'San Clemente'),
(DEFAULT, 9, 'San Javier'),
(DEFAULT, 9, 'San Rafael'),
(DEFAULT, 9, 'Talca'),
(DEFAULT, 9, 'Teno'),
(DEFAULT, 9, 'Vichuquén'),
(DEFAULT, 9, 'Villa Alegre'),
(DEFAULT, 9, 'Yerbas Buenas'),
	
(DEFAULT, 10, 'Bulnes'),
(DEFAULT, 10, 'Chillán'),
(DEFAULT, 10, 'Chillán Viejo'),
(DEFAULT, 10, 'Cobquecura'),
(DEFAULT, 10, 'Coelemu'),
(DEFAULT, 10, 'Coihueco'),
(DEFAULT, 10, 'El Carmen'),
(DEFAULT, 10, 'Ninhue'),
(DEFAULT, 10, 'Ñiquén'),
(DEFAULT, 10, 'Pemuco'),
(DEFAULT, 10, 'Pinto'),
(DEFAULT, 10, 'Portezuelo'),
(DEFAULT, 10, 'Quillón'),
(DEFAULT, 10, 'Quirihue'),
(DEFAULT, 10, 'Ránquil'),
(DEFAULT, 10, 'San Carlos'),
(DEFAULT, 10, 'San Fabián'),
(DEFAULT, 10, 'San Ignacio'),
(DEFAULT, 10, 'San Nicolás'),
(DEFAULT, 10, 'Treguaco'),
(DEFAULT, 10, 'Yungay'),
	
(DEFAULT, 11, 'Alto Biobío'),
(DEFAULT, 11, 'Antuco'),
(DEFAULT, 11, 'Arauco'),
(DEFAULT, 11, 'Cabrero'),
(DEFAULT, 11, 'Cañete'),
(DEFAULT, 11, 'Chiguayante'),
(DEFAULT, 11, 'Concepción'),
(DEFAULT, 11, 'Contulmo'),
(DEFAULT, 11, 'Coronel'),
(DEFAULT, 11, 'Curanilahue'),
(DEFAULT, 11, 'Florida'),
(DEFAULT, 11, 'Hualpén'),
(DEFAULT, 11, 'Hualqui'),
(DEFAULT, 11, 'Laja'),
(DEFAULT, 11, 'Lebu'),
(DEFAULT, 11, 'Los Alamos'),
(DEFAULT, 11, 'Los Angeles'),
(DEFAULT, 11, 'Lota'),
(DEFAULT, 11, 'Mulchén'),
(DEFAULT, 11, 'Nacimiento'),
(DEFAULT, 11, 'Negrete'),
(DEFAULT, 11, 'Penco'),
(DEFAULT, 11, 'Quilaco'),
(DEFAULT, 11, 'Quilleco'),
(DEFAULT, 11, 'San Pedro de la Paz'),
(DEFAULT, 11, 'San Rosendo'),
(DEFAULT, 11, 'Santa Bárbara'),
(DEFAULT, 11, 'Santa Juana'),
(DEFAULT, 11, 'Talcahuano'),
(DEFAULT, 11, 'Tirúa'),
(DEFAULT, 11, 'Tomé'),
(DEFAULT, 11, 'Tucapel'),
(DEFAULT, 11, 'Yumbel'),
	
(DEFAULT, 12, 'Angol'),
(DEFAULT, 12, 'Carahue'),
(DEFAULT, 12, 'Cholchol'),
(DEFAULT, 12, 'Collipulli'),
(DEFAULT, 12, 'Cunco'),
(DEFAULT, 12, 'Curacautín'),
(DEFAULT, 12, 'Curarrehue'),
(DEFAULT, 12, 'Ercilla'),
(DEFAULT, 12, 'Freire'),
(DEFAULT, 12, 'Galvarino'),
(DEFAULT, 12, 'Gorbea'),
(DEFAULT, 12, 'Lautaro'),
(DEFAULT, 12, 'Loncoche'),
(DEFAULT, 12, 'Lonquimay'),
(DEFAULT, 12, 'Los Sauces'),
(DEFAULT, 12, 'Lumaco'),
(DEFAULT, 12, 'Melipeuco'),
(DEFAULT, 12, 'Nueva Imperial'),
(DEFAULT, 12, 'Padre Las Casas'),
(DEFAULT, 12, 'Perquenco'),
(DEFAULT, 12, 'Pitrufquén'),
(DEFAULT, 12, 'Pucón'),
(DEFAULT, 12, 'Purén'),
(DEFAULT, 12, 'Renaico'),
(DEFAULT, 12, 'Saavedra'),
(DEFAULT, 12, 'Temuco'),
(DEFAULT, 12, 'Teodoro Schmidt'),
(DEFAULT, 12, 'Toltén'),
(DEFAULT, 12, 'Traiguén'),
(DEFAULT, 12, 'Victoria'),
(DEFAULT, 12, 'Vilcún'),
(DEFAULT, 12, 'Villarrica'),
	
(DEFAULT, 13, 'Corral'),
(DEFAULT, 13, 'Futrono'),
(DEFAULT, 13, 'Lago Ranco'),
(DEFAULT, 13, 'Lanco'),
(DEFAULT, 13, 'La Unión'),
(DEFAULT, 13, 'Los Lagos'),
(DEFAULT, 13, 'Máfil'),
(DEFAULT, 13, 'Mariquina'),
(DEFAULT, 13, 'Paillaco'),
(DEFAULT, 13, 'Panguipulli'),
(DEFAULT, 13, 'Río Bueno'),
(DEFAULT, 13, 'Valdivia'),
	
(DEFAULT, 14, 'Ancud'),
(DEFAULT, 14, 'Calbuco'),
(DEFAULT, 14, 'Castro'),
(DEFAULT, 14, 'Chaitén'),
(DEFAULT, 14, 'Chonchi'),
(DEFAULT, 14, 'Cochamó'),
(DEFAULT, 14, 'Curaco de Vélez'),
(DEFAULT, 14, 'Dalcahue'),
(DEFAULT, 14, 'Fresia'),
(DEFAULT, 14, 'Frutillar'),
(DEFAULT, 14, 'Futaleufú'),
(DEFAULT, 14, 'Hualaihué'),
(DEFAULT, 14, 'Llanquihue'),
(DEFAULT, 14, 'Los Muermos'),
(DEFAULT, 14, 'Maullín'),
(DEFAULT, 14, 'Osorno'),
(DEFAULT, 14, 'Palena'),
(DEFAULT, 14, 'Puerto Montt'),
(DEFAULT, 14, 'Puerto Octay'),
(DEFAULT, 14, 'Puerto Varas'),
(DEFAULT, 14, 'Puqueldón'),
(DEFAULT, 14, 'Purranque'),
(DEFAULT, 14, 'Puyehue'),
(DEFAULT, 14, 'Queilén'),
(DEFAULT, 14, 'Quellón'),
(DEFAULT, 14, 'Quemchi'),
(DEFAULT, 14, 'Quinchao'),
(DEFAULT, 14, 'Río Negro'),
(DEFAULT, 14, 'San Juan de la Costa'),
(DEFAULT, 14, 'San Pablo'),
	
(DEFAULT, 15, 'Aysén'),
(DEFAULT, 15, 'Chile Chico'),
(DEFAULT, 15, 'Cisnes'),
(DEFAULT, 15, 'Cochrane'),
(DEFAULT, 15, 'Coyhaique'),
(DEFAULT, 15, 'Guaitecas'),
(DEFAULT, 15, 'Lago Verde'),
(DEFAULT, 15, 'O''iggins'),
(DEFAULT, 15, 'Río Ibáñez'),
(DEFAULT, 15, 'Tortel'),
	
(DEFAULT, 16, 'Antártica'),
(DEFAULT, 16, 'Cabo de Hornos'),
(DEFAULT, 16, 'Laguna Blanca'),
(DEFAULT, 16, 'Natales'),
(DEFAULT, 16, 'Porvenir'),
(DEFAULT, 16, 'Primavera'),
(DEFAULT, 16, 'Punta Arenas'),
(DEFAULT, 16, 'Río Verde'),
(DEFAULT, 16, 'San Gregorio'),
(DEFAULT, 16, 'Timaukel'),
(DEFAULT, 16, 'Torres del Paine');
	
